stages:
  - install_deps
  - upload
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
# 安装依赖
install_deps:
  stage: install_deps
  tags:
    - fed
  only:
    - dev
    - master
    - sprint/restart
  script:
    - npm i --registry=http://registry.npm.taobao.org
# 部署测试服务器
upload:
  stage: upload
  tags:
    - fed
  only:
    - dev
    - master
    - sprint/restart
  script:
    - npm run upload -- --commitid `git rev-parse HEAD` --branch $CI_COMMIT_REF_NAME --suffix $CI_PIPELINE_ID
